name: Playwright Tests and SonarQube
on:
    pull_request:
    schedule:
        -   cron: '0 3 * * 0'
    workflow_dispatch:
concurrency:
    group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
    cancel-in-progress: true
jobs:
    playwright:
        timeout-minutes: 5
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v4

            -   uses: actions/setup-node@v4
                with:
                    node-version: lts/*

            -   name: Install dependencies
                run: npm ci

            -   name: Install Playwright Browsers
                run: npx playwright install chromium --with-deps

            -   name: Run Playwright tests
                run: VITE_COVERAGE=true npx playwright test

            -   name: Save code coverage results
                run: npx nyc report --reporter=lcov

            -   uses: actions/upload-artifact@v4
                if: ${{ !cancelled() }}
                with:
                    name: playwright-report
                    path: playwright-report/
                    retention-days: 7

            -   uses: actions/upload-artifact@v4
                if: ${{ !cancelled() }}
                with:
                    name: coverage-report
                    path: coverage/
                    retention-days: 7

    sonarqube:
        runs-on: ubuntu-latest
        needs: [ 'playwright' ]
        steps:
            -   uses: actions/checkout@v4
                with:
                    fetch-depth: 0 # Shallow clones should be disabled for a better relevancy of analysis

            -   name: Download coverage report
                uses: actions/download-artifact@v4
                with:
                    name: coverage-report
                    path: coverage

            -   name: SonarQube Scan
                uses: SonarSource/sonarqube-scan-action@v4
                env:
                    SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
                with:
                    args: >
                        -Dsonar.projectKey=WeCodePixels_theia-sticky-sidebar
                        -Dsonar.organization=wecodepixels
