name: SonarQube

on:
    workflow_run:
        workflows: [ "Playwright Tests" ]
        types:
            - completed

jobs:
    sonarQubeScan:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v4
                with:
                    fetch-depth: 0 # Shallow clones should be disabled for a better relevancy of analysis

            -   name: Download coverage report
                uses: dawidd6/action-download-artifact@v3
                with:
                    workflow: playwright.yml
                    name: coverage-report
                    path: coverage

            -   name: SonarQube Scan
                uses: SonarSource/sonarqube-scan-action@v4
                env:
                    SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
                with:
                    projectBaseDir: lib
                    args: >
                        -Dsonar.projectKey=WeCodePixels_theia-sticky-sidebar
                        -Dsonar.organization=wecodepixels
